### ISSUE TITLE
can‘t download

### ISSUE THREAD

**Issue by goxofy** [fraserxu/music163-cli#2]
$>music163 download -t playlist 9851196                  
                                                     
path.js:360
        throw new TypeError('Arguments to path.join must be strings');
              ^
TypeError: Arguments to path.join must be strings
    at path.js:360:15
    at Array.filter (native)
    at Object.exports.join (path.js:358:36)
    at download (/usr/lib/node_modules/music163-cli/bin/cmd.js:234:22)
    at /usr/lib/node_modules/music163-cli/bin/cmd.js:114:5
    at /usr/lib/node_modules/music163-cli/bin/cmd.js:153:7
    at /usr/lib/node_modules/music163-cli/node_modules/music163/index.js:74:14
    at ConcatStream.<anonymous> (/usr/lib/node_modules/music163-cli/node_modules/music163/node_modules/concat-stream/index.js:32:43)
    at ConcatStream.EventEmitter.emit (events.js:92:17)
    at finishMaybe (/usr/lib/node_modules/music163-cli/node_modules/music163/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:460:14)

**Comment by fraserxu** [comment]
My bad, forget to pass in the dist params. You can try this.
```
music163 download -t playlist -d Desktop 9851196
```

**Comment by goxofy** [comment]
thanks！
