### ISSUE TITLE
node-gyp rebulid error

### ISSUE THREAD

**Issue by holidaybattle** [fraserxu/music163-cli#5]
4261 error Windows_NT 6.1.7601
4262 error argv "E:\\nodejs\\\\node.exe" "E:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "music163-cli" "-g"
4263 error node v0.12.2
4264 error npm  v2.7.5
4265 error code ELIFECYCLE
4266 error speaker@0.0.10 install: `node-gyp rebuild`
4266 error Exit status 1
4267 error Failed at the speaker@0.0.10 install script 'node-gyp rebuild'.
4267 error This is most likely a problem with the speaker package,
4267 error not with npm itself.
4267 error Tell the author that this fails on your system:
4267 error     node-gyp rebuild
4267 error You can get their info via:
4267 error     npm owner ls speaker
4267 error There is likely additional logging output above.
4268 verbose exit [ 1, true ]
4269 verbose unbuild node_modules\music163-cli\node_modules\speaker
4270 info preuninstall speaker@0.0.10
4271 info uninstall speaker@0.0.10
4272 verbose unbuild rmStuff speaker@0.0.10 from E:\nodejs\node_modules
4273 verbose unbuild rmStuff in E:\nodejs\node_modules\music163-cli\node_modules
4274 info postuninstall speaker@0.0.10
4275 silly gentlyRm E:\nodejs\node_modules\music163-cli\node_modules\speaker is being purged from base E:\nodejs
4276 verbose gentlyRm don't care about contents; nuking E:\nodejs\node_modules\music163-cli\node_modules\speaker
4277 silly vacuum-fs purging E:\nodejs\node_modules\music163-cli\node_modules\speaker
4278 silly vacuum-fs quitting because other entries in E:\nodejs\node_modules\music163-cli\node_modules
4279 verbose unbuild node_modules\music163-cli\node_modules\lame
4280 info preuninstall lame@1.0.3
4281 info uninstall lame@1.0.3
4282 verbose unbuild rmStuff lame@1.0.3 from E:\nodejs\node_modules
4283 verbose unbuild rmStuff in E:\nodejs\node_modules\music163-cli\node_modules
4284 info postuninstall lame@1.0.3
4285 silly gentlyRm E:\nodejs\node_modules\music163-cli\node_modules\lame is being purged from base E:\nodejs
4286 verbose gentlyRm don't care about contents; nuking E:\nodejs\node_modules\music163-cli\node_modules\lame
4287 silly vacuum-fs purging E:\nodejs\node_modules\music163-cli\node_modules\lame
4288 silly vacuum-fs quitting because other entries in E:\nodejs\node_modules\music163-cli\node_modules
4289 verbose unbuild node_modules\music163-cli

**Comment by bkakatze** [comment]
I have the same issue

`bka@Spinnenbru ~ % sudo npm install -g music163-cli                                                      
/usr/bin/music163 -> /usr/lib/node_modules/music163-cli/bin/cmd.js

> speaker@0.2.5 install /usr/lib/node_modules/music163-cli/node_modules/speaker
> node-gyp rebuild

make: Verzeichnis „/usr/lib/node_modules/music163-cli/node_modules/speaker/build“ wird betreten
  CC(target) Release/obj.target/output/deps/mpg123/src/output/alsa.o
../deps/mpg123/src/output/alsa.c: In Funktion »initialize_device«:
../deps/mpg123/src/output/alsa.c:78:16: Warnung: Vergleich zwischen vorzeichenbehafteten und vorzeichenlosen Ganzzahlausdrücken [-Wsign-compare]
  for (i = 0; i < NUM_FORMATS; ++i) {
                ^
../deps/mpg123/src/output/alsa.c: In Funktion »get_formats_alsa«:
../deps/mpg123/src/output/alsa.c:201:16: Warnung: Vergleich zwischen vorzeichenbehafteten und vorzeichenlosen Ganzzahlausdrücken [-Wsign-compare]
  for (i = 0; i < NUM_FORMATS; ++i) {
                ^
  AR(target) Release/obj.target/deps/mpg123/liboutput.a
  COPY Release/liboutput.a
  CXX(target) Release/obj.target/binding/src/binding.o
In file included from ../node_modules/nan/nan_new.h:190:0,
                 from ../node_modules/nan/nan.h:80,
                 from ../src/node_pointer.h:7,
                 from ../src/binding.cc:8:
../node_modules/nan/nan_implementation_12_inl.h: In statischer Elementfunktion »static NanIntern::FactoryBase<v8::Signature>::return_t NanIntern::Factory<v8::Signature>::New(NanIntern::Factory<v8::Signature>::FTH, int, NanIntern::Factory<v8::Signature>::FTH*)«:
../node_modules/nan/nan_implementation_12_inl.h:181:76: Fehler: keine passende Funktion für Aufruf von »v8::Signature::New(v8::Isolate*, NanIntern::Factory<v8::Signature>::FTH&, int&, NanIntern::Factory<v8::Signature>::FTH*&)«
   return v8::Signature::New(v8::Isolate::GetCurrent(), receiver, argc, argv);
                                                                            ^
In file included from ../src/binding.cc:5:0:
/root/.node-gyp/5.5.0/include/node/v8.h:4674:27: Anmerkung: candidate: static v8::Local<v8::Signature> v8::Signature::New(v8::Isolate*, v8::Local<v8::FunctionTemplate>)
   static Local<Signature> New(
                           ^
/root/.node-gyp/5.5.0/include/node/v8.h:4674:27: Anmerkung:   Kandidat erwartet 2 Argumente, 4 angegeben
In file included from ../src/node_pointer.h:7:0,
                 from ../src/binding.cc:8:
../node_modules/nan/nan.h: Im globalen Gültigkeitsbereich:
../node_modules/nan/nan.h:171:25: Fehler: Redefinition von »template<class T> v8::Local<T> _NanEnsureLocal(v8::Local<T>)«
 NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                         ^
../node_modules/nan/nan.h:166:25: Anmerkung: »template<class T> v8::Local<T> _NanEnsureLocal(v8::Handle<T>)« wurde bereits hier deklariert
 NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
                         ^
../node_modules/nan/nan.h:564:13: Fehler: »node::smalloc« wurde nicht deklariert
     , node::smalloc::FreeCallback callback
             ^
../node_modules/nan/nan.h:564:35: Fehler: expected »,« or »...« before »callback«
     , node::smalloc::FreeCallback callback
                                   ^
../node_modules/nan/nan.h: In Funktion »v8::Local<v8::Object> NanNewBufferHandle(char*, size_t, int)«:
../node_modules/nan/nan.h:568:50: Fehler: »callback« wurde in diesem Gültigkeitsbereich nicht definiert
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                  ^
../node_modules/nan/nan.h:568:60: Fehler: »hint« wurde in diesem Gültigkeitsbereich nicht definiert
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                            ^
../node_modules/nan/nan.h: In Funktion »v8::Local<v8::Object> NanNewBufferHandle(const char*, uint32_t)«:
../node_modules/nan/nan.h:575:67: Fehler: keine passende Funktion für Aufruf von »New(v8::Isolate*, const char*&, uint32_t&)«
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
In file included from ../node_modules/nan/nan.h:25:0,
                 from ../src/node_pointer.h:7,
                 from ../src/binding.cc:8:
/root/.node-gyp/5.5.0/include/node/node_buffer.h:31:40: Anmerkung: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) <nahe Übereinstimmung>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/root/.node-gyp/5.5.0/include/node/node_buffer.h:31:40: Anmerkung:   Umwandlung von Argument 3 wäre unzulässig:
In file included from ../src/node_pointer.h:7:0,
                 from ../src/binding.cc:8:
../node_modules/nan/nan.h:575:67: Fehler: ungültige Umwandlung von »uint32_t {aka unsigned int}« in »node::encoding« [-fpermissive]
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
In file included from ../node_modules/nan/nan.h:25:0,
                 from ../src/node_pointer.h:7,
                 from ../src/binding.cc:8:
/root/.node-gyp/5.5.0/include/node/node_buffer.h:43:40: Anmerkung: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t) <nahe Übereinstimmung>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/root/.node-gyp/5.5.0/include/node/node_buffer.h:43:40: Anmerkung:   Umwandlung von Argument 2 wäre unzulässig:
In file included from ../src/node_pointer.h:7:0,
                 from ../src/binding.cc:8:
../node_modules/nan/nan.h:575:67: Fehler: ungültige Umwandlung von »const char*« in »char*« [-fpermissive]
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
../node_modules/nan/nan.h: In Funktion »v8::Local<v8::Object> NanNewBufferHandle(uint32_t)«:
../node_modules/nan/nan.h:579:29: Fehler: »node::Buffer::New(v8::Isolate::GetCurrent(), ((size_t)size))« konnte nicht von »v8::MaybeLocal<v8::Object>« nach »v8::Local<v8::Object>« umgewandelt werden
     return node::Buffer::New(v8::Isolate::GetCurrent(), size);
                             ^
../node_modules/nan/nan.h: In Funktion »v8::Local<v8::Object> NanBufferUse(char*, uint32_t)«:
../node_modules/nan/nan.h:586:12: Fehler: »Use« ist kein Element von »node::Buffer«
     return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
            ^
In file included from ../src/binding.cc:8:0:
../src/node_pointer.h: In Funktion »v8::Handle<v8::Value> WrapPointer(void*, size_t)«:
../src/node_pointer.h:24:76: Fehler: keine passende Funktion für Aufruf von »NanNewBufferHandle(char*, size_t&, void (&)(char*, void*), void*&)«
   return NanNewBufferHandle((char *)ptr, length, wrap_pointer_cb, user_data);
                                                                            ^
In file included from ../src/node_pointer.h:7:0,
                 from ../src/binding.cc:8:
../node_modules/nan/nan.h:561:36: Anmerkung: candidate: v8::Local<v8::Object> NanNewBufferHandle(char*, size_t, int)
   NAN_INLINE v8::Local<v8::Object> NanNewBufferHandle (
                                    ^
../node_modules/nan/nan.h:561:36: Anmerkung:   Kandidat erwartet 3 Argumente, 4 angegeben
../node_modules/nan/nan.h:571:36: Anmerkung: candidate: v8::Local<v8::Object> NanNewBufferHandle(const char*, uint32_t)
   NAN_INLINE v8::Local<v8::Object> NanNewBufferHandle (
                                    ^
../node_modules/nan/nan.h:571:36: Anmerkung:   Kandidat erwartet 2 Argumente, 4 angegeben
../node_modules/nan/nan.h:578:36: Anmerkung: candidate: v8::Local<v8::Object> NanNewBufferHandle(uint32_t)
   NAN_INLINE v8::Local<v8::Object> NanNewBufferHandle (uint32_t size) {
                                    ^
../node_modules/nan/nan.h:578:36: Anmerkung:   Kandidat erwartet 1 Argument, 4 angegeben
binding.target.mk:101: die Regel für Ziel „Release/obj.target/binding/src/binding.o“ scheiterte
make: *** [Release/obj.target/binding/src/binding.o] Fehler 1
make: Verzeichnis „/usr/lib/node_modules/music163-cli/node_modules/speaker/build“ wird verlassen
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.3.3-3-ARCH
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/music163-cli/node_modules/speaker
gyp ERR! node -v v5.5.0
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok 
/usr/lib
└── (empty)

npm ERR! Linux 4.3.3-3-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "music163-cli"
npm ERR! node v5.5.0
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE

npm ERR! speaker@0.2.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the speaker@0.2.5 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the speaker package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs speaker
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls speaker
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/bka/npm-debug.log
npm ERR! code 1
sudo npm install -g music163-cli  5,47s user 0,43s system 55% cpu 10,645 total
1 bka@Spinnenbru ~ %                                                                                  :( 

`
